_target_: src.models.diffusion_module.DiffusionModule

t_range: 1000
in_size: 32
img_depth: 3


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.my_unet.AttentionUnet
  img_depth: ${model.img_depth}
  device: ${trainer.accelerator}

# compile model for faster training with pytorch 2.0
compile: false
